piVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1ERXlNekU1TWpZME9Gb1hEVE14TURFeU1URTVNalkwT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHVqCkpHWTl4WDNhcmF4NzNGMWlPSFVGaFdTWmMvSmFaU2RydTFjOWw5UzBUU1FVcEVQYjA5cjV2V2YyRDZpMHVYQ2gKZC9zMURWcVZyUi9JTHRqM3JxYlJsZ2JROW5YcExHcTdPZjN0ODU3bDFvdHphWlh6YnlINm8yNXpXS1VhQWlaWQpLV3lHTHU0TTJ2UzJTdktUUFlsd09aejhRd3FIU20wbUwxb1NiZnJrU2lXWUFRS1lENFZEYmZXbEl1VE9IY3M4Ck54TXVIZUVQcy9FM2VUdUVlUnNKV2VRR3V2cS9NZUxqaUduSnBpRG01UnpwMm9ieE4wSE1CaXhjSjRrb2V4ZlMKWEJ6cHNzVXpRMitjVE4yelhxeHRLcXEzdDFuU1lIMHN5YjJ2WnVveFN4LzJGZDNDME1UbzRDcnJqVlBaZGRRdAp4SzkzQlp6cnpvM3dDdUVuVGFNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBeldnUDJhbEZ6aG1UWjl0ZVhVaDhDYS9WK2MKWjMvVU13cFRQRHVCNktFSG12R1Njd2tSVy9sMjhtWkltZktNbytkbmNjWmN0OHJUUGFnamR2YjlqelF1VEZvdgovM1RxanlSY21mcE1oUkxYOHpWNlY0R1VnMlpDdFgyWUFSWHZRV3ExelY2VmhUM0Fack5FZVF6TUROSzFJMUZ0Cjg5S0JjQnIzdHI2UzZpYlhCeXZnbmpObWtQWGd5ajd4c3U3V1hhRHM5V1AyWnVLWjVEaHRRK0FETmlXUnh6cTQKejB2V21jTjZjMk54bkh1WDVDN0ZPWnBwMUg3SmdWUkoyQVV3UVE1TTVWaERpNzhnZHBCeE9kOStaQktYT0dhQgpHczJONkVKdjdSZC95bW90WVErUU5QNmtLell2bGJ2VDNhbk5iNG5OTFJxRExyZDJNY2xnWnY1c2o3ST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://80dec6c0-4136-4262-8a2b-712fb3da39c2.us-east-1.linodelke.net:443
  name: lke17572

users:
- name: lke17572-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkdQUmpqTW5iZmpXOXFGU09kckltbHB6Y0FpdlFKRlBFUzZ6QXh2aXNlNDgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4td2xka2wiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZDc5NTg2ZjgtZDI5Ni00MDk1LWI4MmUtOWFlZTJlMzJhNTVjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.L25646deEGVBXLt0SZYnjp__zvc_Cv5jwCPpHOS8ulGAGNWZ3YWvGHJXTm34awwPUIMOFZsPfZfsuhmYbk7pG1Ut8R0Go3VvfgYVfeSI9ga76dtPXBgb5sGU_4-ExPp0OON5GEpEVXHa93KUKO9ExVtu5rYpao0O6Vv_sz5oI1s_w5VOezjIAMDkjInXJ7DppLzEHEwtWXFc8aqyrGYb_ejUAFHYtzxjm-F_4LzSygEDmQokfirWfIZVlvlnVi0Xtp3ja1zXEryAqxNww-wbDZyO0mIMr7le9QxeDJc0apPSJgUmCgdVFQGNr00HDQmmWyZQMgTTJuqhTBqjctcZiA

contexts:
- context:
    cluster: lke17572
    namespace: default
    user: lke17572-admin
  name: lke17572-ctx

current-context: lke17572-ctx

