---
- hosts: build_host
  gather_facts: no
  become: true
  user: root
  
  tasks:
    - name: create build directory
      file:
        path: /root/demo-dockerfile
        state: directory
        owner: root
        group: root
        mode: '0755'

    -  name: copy docker compose file
       command: git clone https://github.com/BrianSandiford/REST-API-DOCKER-SQLALCHEMY.git
       ignore_errors: yes
       args:
        chdir: /root/demo-dockerfile/

    -  name: pull docker compose file
       command: git pull https://github.com/BrianSandiford/REST-API-DOCKER-SQLALCHEMY.git
       ignore_errors: yes
       args:
        chdir: /root/demo-dockerfile/REST-API-DOCKER-SQLALCHEMY/

    -  name: copy path.xml to local directory
       command: docker cp test_app_1:/app/path.xml ./reports
       args:
        chdir: /root/demo-dockerfile/REST-API-DOCKER-SQLALCHEMY/
#      become: yes 
#    - name: copy docker compose file
#      become: yes
#      copy:
#        src: /var/lib/jenkins/workspace/test
#        dest: /root/demo-dockerfile/
#        owner: root
#        group: root
#        mode: '0644'

    - name: remove docker image
      become: yes
      command: docker rmi demodockerfileapp
      ignore_errors: yes

    - name: build container image
      become: yes
      command: docker-compose up -d --build
     # command: docker build -t demodockerfileapp .
      args:
        chdir: /root/demo-dockerfile/REST-API-DOCKER-SQLALCHEMY/

    
    
