---
- hosts: build_host
  gather_facts: no
  become: true
  user: root
  
  tasks:
    - name: create build directory
      file:
        path: /root/demo-dockerfile
        state: directory
        owner: root
        group: root
        mode: '0755'

    -  name: copy docker compose file
       command: git clone https://github.com/BrianSandiford/REST-API-DOCKER-SQLALCHEMY.git
       ignore_errors: yes
       args:
        chdir: /root/demo-dockerfile/

    -  name: pull docker compose file
       command: git pull https://github.com/BrianSandiford/REST-API-DOCKER-SQLALCHEMY.git
       ignore_errors: yes
       args:
        chdir: /root/demo-dockerfile/REST-API-DOCKER-SQLALCHEMY/

    - name: remove docker image
      command: docker rmi demodockerfileapp
      ignore_errors: yes

    - name: start docker
      command: systemctl start docker

    - name: build container image
      command: docker-compose up -d --build
     # command: docker build -t demodockerfileapp .
      args:
        chdir: /root/demo-dockerfile/REST-API-DOCKER-SQLALCHEMY/

    
    
