---
- hosts: build_host
  gather_facts: no
  tasks:
    - name: create build directory
      become: yes
      file:
        path: /root/demo-dockerfile
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy docker compose file
      become: yes
      copy:
        src: /var/lib/jenkins/workspace/test
        dest: /root/demo-dockerfile/
        owner: root
        group: root
        mode: '0644'

    - name: remove docker image
      become: yes
      command: docker rmi demodockerfileapp
      ignore_errors: yes

    - name: build container image
      become: yes
      command: docker-compose up -d --build
     # command: docker build -t demodockerfileapp .
      args:
        chdir: /root/demo-dockerfile/test/

    
    
