apiVersion: v1
kind: Service
metadata:
  name: restapi-service
spec:
  selector:
    app: restapi
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
spec:
  selector:
    matchLabels:
      app: restapi
  replicas: 4
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - name: restapi
        image: briansandiford/restapi:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5000
