version: '3.5'

services:
  database:
    container_name: postgres
    image: postgres:latest
    env_file: database.env
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql

  app:
   build:
    context: .
   dockerfile: Dockerfile
   image: demodockerfileapp
   env_file: database.env
   ports:
     - 5000:5000
     - 5678:5678
   #volumes:
   #  - ./src/example/:/app/example
   environment:
#      - FLASK_APP=src/example/app.py
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig  
       
   depends_on:
     - database
    
volumes:
  db_volume:
  app_volume:
