---
- hosts: build_host
  vars:
    PASS: inr2mtidne
  gather_facts: no
  tasks:
    - name: login to docker
      become: yes
      command: docker login -u briansandiford -p "{{ PASS }}"
    
    - name: push image to dockerhub
      become: yes
      command: docker push briansandiford/demodockerfileapp
