---
- hosts: build_host
  gather_facts: no
  tasks:
    - name: create tag to image
      become: yes
      command: docker tag demodockerfileapp briansandiford/demodockerfileapp

    - name: login to docker
      become: yes
      command: docker login -u briansandiford -p $PASS
    
    - name: push image to dockerhub
      become: yes
      command: docker push briansandiford/demodockerfileapp

    - name: remove docker images from build server
      become: yes
      command: docker rmi demodockerfileapp briansandiford/demodockerfileapp
      ignore_errors: yes
     
